version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
